---
title: Xbox Discord - A bot for Xbox clips, screenshots, and more
author: NightSurgeX2
email: support@gamerdvr.com
description: Xbox Discord is a Discord bot for finding your Xbox clips, screenshots,
  achievements, and more. Constantly updating features based on community feedback.
  If you have xbox and discord, get this bot now!
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
